def generate_init_file():

    from glob import glob
    
    files  = glob('*.py')
    files = [_ for _ in files if not _.startswith('__')]

    contents = []
    for file in files:
        file_name = file.split('.')[0]
        line = f'from .{file_name} import {file_name}'
        contents.append(line)

    contents = '\n'.join(contents)
    print(contents)
    
    with open('__init__.py', "w", encoding="utf-8") as f:
        f.write(contents)


generate_init_file()
